//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace forAzeroth.Models
{
    using Microsoft.EntityFrameworkCore;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using DbContext = System.Data.Entity.DbContext;

    public partial class WoWBaseEntities : DbContext
    {
        public WoWBaseEntities()
            : base("name=WoWBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual System.Data.Entity.DbSet<Table> Tables { get; set; }
        public virtual System.Data.Entity.DbSet<WoW> WoWs { get; set; }
    }
}
